### ISSUE TITLE
Budget app Csharp Godot 4 video repo

### ISSUE THREAD

**Issue by canloe** [finepointcgi/FinepointCGI-Suggestions#64]
Hi, I'm working through your budget app video here: https://www.youtube.com/watch?v=knEZar7u6l4

I can't find the assets you use (csv file and pie pieces png images) in the video on your github.

Could you upload those files, or the repo for that project? Thank you.

**Comment by finepointcgi** [comment]
sorry about that here you go
https://github.com/finepointcgi/Budgeting-App

**Comment by finepointcgi** [comment]
heres a direct link to it
https://github.com/finepointcgi/Budgeting-App/blob/master/AccountHistory.csv
